language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
addons:
  postgresql: '9.6'
cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=ci
before_script:
  - npm install coveralls
script:
  - npm run test
notifications:
  email: false