http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  businessDate:
    host: localhost
    paths: ['/api/v1/businessDates', '/api/v1/businessDates/*']
  pubsub:
    host: localhost
    paths: ['/api/v1/subscriptions','/api/v1/subscriptions/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  businessDatesService:
    url: 'http://localhost:8081'
  pubsubService:
     url: 'http://localhost:8082'
    
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  businessDatesPipeLine:
    apiEndpoints:
      - businessDates
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: businessDatesService
              changeOrigin: true
  pubSubPipeLine:
    apiEndpoints:
        - pubSub
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: pubsubService
              changeOrigin: true
